// Code generated by Kitex v0.15.4. DO NOT EDIT.

package imagemoderationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	safeflow "github.com/safeflow-project/safeflow/kitex_gen/safeflow"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Moderate": kitex.NewMethodInfo(
		moderateHandler,
		newImageModerationServiceModerateArgs,
		newImageModerationServiceModerateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	imageModerationServiceServiceInfo                = NewServiceInfo()
	imageModerationServiceServiceInfoForClient       = NewServiceInfoForClient()
	imageModerationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return imageModerationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return imageModerationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return imageModerationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ImageModerationService"
	handlerType := (*safeflow.ImageModerationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "safeflow",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func moderateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*safeflow.ImageModerationServiceModerateArgs)
	realResult := result.(*safeflow.ImageModerationServiceModerateResult)
	success, err := handler.(safeflow.ImageModerationService).Moderate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newImageModerationServiceModerateArgs() interface{} {
	return safeflow.NewImageModerationServiceModerateArgs()
}

func newImageModerationServiceModerateResult() interface{} {
	return safeflow.NewImageModerationServiceModerateResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Moderate(ctx context.Context, req *safeflow.ImageModerationRequest) (r *safeflow.ImageModerationResponse, err error) {
	var _args safeflow.ImageModerationServiceModerateArgs
	_args.Req = req
	var _result safeflow.ImageModerationServiceModerateResult
	if err = p.c.Call(ctx, "Moderate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
