// Code generated by Kitex v0.15.4. DO NOT EDIT.

package llmagentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	safeflow "github.com/safeflow-project/safeflow/kitex_gen/safeflow"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Scan": kitex.NewMethodInfo(
		scanHandler,
		newLLMAgentServiceScanArgs,
		newLLMAgentServiceScanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	lLMAgentServiceServiceInfo                = NewServiceInfo()
	lLMAgentServiceServiceInfoForClient       = NewServiceInfoForClient()
	lLMAgentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return lLMAgentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return lLMAgentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return lLMAgentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LLMAgentService"
	handlerType := (*safeflow.LLMAgentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "safeflow",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func scanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*safeflow.LLMAgentServiceScanArgs)
	realResult := result.(*safeflow.LLMAgentServiceScanResult)
	success, err := handler.(safeflow.LLMAgentService).Scan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLLMAgentServiceScanArgs() interface{} {
	return safeflow.NewLLMAgentServiceScanArgs()
}

func newLLMAgentServiceScanResult() interface{} {
	return safeflow.NewLLMAgentServiceScanResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Scan(ctx context.Context, req *safeflow.ScanRequest) (r *safeflow.ScanResponse, err error) {
	var _args safeflow.LLMAgentServiceScanArgs
	_args.Req = req
	var _result safeflow.LLMAgentServiceScanResult
	if err = p.c.Call(ctx, "Scan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
