// Code generated by Kitex v0.15.4. DO NOT EDIT.
package ruleengineservice

import (
	server "github.com/cloudwego/kitex/server"
	safeflow "github.com/safeflow-project/safeflow/kitex_gen/safeflow"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler safeflow.RuleEngineService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler safeflow.RuleEngineService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
