// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package safeflow

import (
	"context"
	"fmt"
)

type ScanRequest struct {
	RequestId string `thrift:"request_id,1" frugal:"1,default,string" json:"request_id"`
	UserId    string `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	Content   string `thrift:"content,3" frugal:"3,default,string" json:"content"`
}

func NewScanRequest() *ScanRequest {
	return &ScanRequest{}
}

func (p *ScanRequest) InitDefault() {
}

func (p *ScanRequest) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ScanRequest) GetUserId() (v string) {
	return p.UserId
}

func (p *ScanRequest) GetContent() (v string) {
	return p.Content
}
func (p *ScanRequest) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ScanRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *ScanRequest) SetContent(val string) {
	p.Content = val
}

func (p *ScanRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScanRequest(%+v)", *p)
}

var fieldIDToName_ScanRequest = map[int16]string{
	1: "request_id",
	2: "user_id",
	3: "content",
}

type ScanResponse struct {
	RequestId string `thrift:"request_id,1" frugal:"1,default,string" json:"request_id"`
	Action    string `thrift:"action,2" frugal:"2,default,string" json:"action"`
	Reason    string `thrift:"reason,3" frugal:"3,default,string" json:"reason"`
	Source    string `thrift:"source,4" frugal:"4,default,string" json:"source"`
}

func NewScanResponse() *ScanResponse {
	return &ScanResponse{}
}

func (p *ScanResponse) InitDefault() {
}

func (p *ScanResponse) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ScanResponse) GetAction() (v string) {
	return p.Action
}

func (p *ScanResponse) GetReason() (v string) {
	return p.Reason
}

func (p *ScanResponse) GetSource() (v string) {
	return p.Source
}
func (p *ScanResponse) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ScanResponse) SetAction(val string) {
	p.Action = val
}
func (p *ScanResponse) SetReason(val string) {
	p.Reason = val
}
func (p *ScanResponse) SetSource(val string) {
	p.Source = val
}

func (p *ScanResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScanResponse(%+v)", *p)
}

var fieldIDToName_ScanResponse = map[int16]string{
	1: "request_id",
	2: "action",
	3: "reason",
	4: "source",
}

type Box struct {
	X1 int32 `thrift:"x1,1" frugal:"1,default,i32" json:"x1"`
	Y1 int32 `thrift:"y1,2" frugal:"2,default,i32" json:"y1"`
	X2 int32 `thrift:"x2,3" frugal:"3,default,i32" json:"x2"`
	Y2 int32 `thrift:"y2,4" frugal:"4,default,i32" json:"y2"`
}

func NewBox() *Box {
	return &Box{}
}

func (p *Box) InitDefault() {
}

func (p *Box) GetX1() (v int32) {
	return p.X1
}

func (p *Box) GetY1() (v int32) {
	return p.Y1
}

func (p *Box) GetX2() (v int32) {
	return p.X2
}

func (p *Box) GetY2() (v int32) {
	return p.Y2
}
func (p *Box) SetX1(val int32) {
	p.X1 = val
}
func (p *Box) SetY1(val int32) {
	p.Y1 = val
}
func (p *Box) SetX2(val int32) {
	p.X2 = val
}
func (p *Box) SetY2(val int32) {
	p.Y2 = val
}

func (p *Box) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Box(%+v)", *p)
}

var fieldIDToName_Box = map[int16]string{
	1: "x1",
	2: "y1",
	3: "x2",
	4: "y2",
}

type Label struct {
	Name       string  `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Confidence float64 `thrift:"confidence,2" frugal:"2,default,double" json:"confidence"`
}

func NewLabel() *Label {
	return &Label{}
}

func (p *Label) InitDefault() {
}

func (p *Label) GetName() (v string) {
	return p.Name
}

func (p *Label) GetConfidence() (v float64) {
	return p.Confidence
}
func (p *Label) SetName(val string) {
	p.Name = val
}
func (p *Label) SetConfidence(val float64) {
	p.Confidence = val
}

func (p *Label) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Label(%+v)", *p)
}

var fieldIDToName_Label = map[int16]string{
	1: "name",
	2: "confidence",
}

type ImageModerationRequest struct {
	RequestId string `thrift:"request_id,1" frugal:"1,default,string" json:"request_id"`
	ImageUrl  string `thrift:"image_url,2" frugal:"2,default,string" json:"image_url"`
	ImageData []byte `thrift:"image_data,3" frugal:"3,default,binary" json:"image_data"`
	Scene     string `thrift:"scene,4" frugal:"4,default,string" json:"scene"`
	EnableOcr bool   `thrift:"enable_ocr,5" frugal:"5,default,bool" json:"enable_ocr"`
}

func NewImageModerationRequest() *ImageModerationRequest {
	return &ImageModerationRequest{}
}

func (p *ImageModerationRequest) InitDefault() {
}

func (p *ImageModerationRequest) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ImageModerationRequest) GetImageUrl() (v string) {
	return p.ImageUrl
}

func (p *ImageModerationRequest) GetImageData() (v []byte) {
	return p.ImageData
}

func (p *ImageModerationRequest) GetScene() (v string) {
	return p.Scene
}

func (p *ImageModerationRequest) GetEnableOcr() (v bool) {
	return p.EnableOcr
}
func (p *ImageModerationRequest) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ImageModerationRequest) SetImageUrl(val string) {
	p.ImageUrl = val
}
func (p *ImageModerationRequest) SetImageData(val []byte) {
	p.ImageData = val
}
func (p *ImageModerationRequest) SetScene(val string) {
	p.Scene = val
}
func (p *ImageModerationRequest) SetEnableOcr(val bool) {
	p.EnableOcr = val
}

func (p *ImageModerationRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageModerationRequest(%+v)", *p)
}

var fieldIDToName_ImageModerationRequest = map[int16]string{
	1: "request_id",
	2: "image_url",
	3: "image_data",
	4: "scene",
	5: "enable_ocr",
}

type ImageModerationResponse struct {
	RequestId   string      `thrift:"request_id,1" frugal:"1,default,string" json:"request_id"`
	Action      string      `thrift:"action,2" frugal:"2,default,string" json:"action"`
	RiskScore   float64     `thrift:"risk_score,3" frugal:"3,default,double" json:"risk_score"`
	TextContent string      `thrift:"text_content,4" frugal:"4,default,string" json:"text_content"`
	Labels      []*Label    `thrift:"labels,5" frugal:"5,default,list<Label>" json:"labels"`
	Reason      string      `thrift:"reason,6" frugal:"6,default,string" json:"reason"`
	OcrResult_  *OCRResult_ `thrift:"ocr_result,7" frugal:"7,default,OCRResult_" json:"ocr_result"`
}

func NewImageModerationResponse() *ImageModerationResponse {
	return &ImageModerationResponse{}
}

func (p *ImageModerationResponse) InitDefault() {
}

func (p *ImageModerationResponse) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ImageModerationResponse) GetAction() (v string) {
	return p.Action
}

func (p *ImageModerationResponse) GetRiskScore() (v float64) {
	return p.RiskScore
}

func (p *ImageModerationResponse) GetTextContent() (v string) {
	return p.TextContent
}

func (p *ImageModerationResponse) GetLabels() (v []*Label) {
	return p.Labels
}

func (p *ImageModerationResponse) GetReason() (v string) {
	return p.Reason
}

var ImageModerationResponse_OcrResult__DEFAULT *OCRResult_

func (p *ImageModerationResponse) GetOcrResult_() (v *OCRResult_) {
	if !p.IsSetOcrResult_() {
		return ImageModerationResponse_OcrResult__DEFAULT
	}
	return p.OcrResult_
}
func (p *ImageModerationResponse) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ImageModerationResponse) SetAction(val string) {
	p.Action = val
}
func (p *ImageModerationResponse) SetRiskScore(val float64) {
	p.RiskScore = val
}
func (p *ImageModerationResponse) SetTextContent(val string) {
	p.TextContent = val
}
func (p *ImageModerationResponse) SetLabels(val []*Label) {
	p.Labels = val
}
func (p *ImageModerationResponse) SetReason(val string) {
	p.Reason = val
}
func (p *ImageModerationResponse) SetOcrResult_(val *OCRResult_) {
	p.OcrResult_ = val
}

func (p *ImageModerationResponse) IsSetOcrResult_() bool {
	return p.OcrResult_ != nil
}

func (p *ImageModerationResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageModerationResponse(%+v)", *p)
}

var fieldIDToName_ImageModerationResponse = map[int16]string{
	1: "request_id",
	2: "action",
	3: "risk_score",
	4: "text_content",
	5: "labels",
	6: "reason",
	7: "ocr_result",
}

type OCRResult_ struct {
	ExtractedText string       `thrift:"extracted_text,1" frugal:"1,default,string" json:"extracted_text"`
	Confidence    float64      `thrift:"confidence,2" frugal:"2,default,double" json:"confidence"`
	TextBlocks    []*TextBlock `thrift:"text_blocks,3" frugal:"3,default,list<TextBlock>" json:"text_blocks"`
	Language      string       `thrift:"language,4" frugal:"4,default,string" json:"language"`
}

func NewOCRResult_() *OCRResult_ {
	return &OCRResult_{}
}

func (p *OCRResult_) InitDefault() {
}

func (p *OCRResult_) GetExtractedText() (v string) {
	return p.ExtractedText
}

func (p *OCRResult_) GetConfidence() (v float64) {
	return p.Confidence
}

func (p *OCRResult_) GetTextBlocks() (v []*TextBlock) {
	return p.TextBlocks
}

func (p *OCRResult_) GetLanguage() (v string) {
	return p.Language
}
func (p *OCRResult_) SetExtractedText(val string) {
	p.ExtractedText = val
}
func (p *OCRResult_) SetConfidence(val float64) {
	p.Confidence = val
}
func (p *OCRResult_) SetTextBlocks(val []*TextBlock) {
	p.TextBlocks = val
}
func (p *OCRResult_) SetLanguage(val string) {
	p.Language = val
}

func (p *OCRResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OCRResult_(%+v)", *p)
}

var fieldIDToName_OCRResult_ = map[int16]string{
	1: "extracted_text",
	2: "confidence",
	3: "text_blocks",
	4: "language",
}

type TextBlock struct {
	Text        string  `thrift:"text,1" frugal:"1,default,string" json:"text"`
	Confidence  float64 `thrift:"confidence,2" frugal:"2,default,double" json:"confidence"`
	BoundingBox *Box    `thrift:"bounding_box,3" frugal:"3,default,Box" json:"bounding_box"`
}

func NewTextBlock() *TextBlock {
	return &TextBlock{}
}

func (p *TextBlock) InitDefault() {
}

func (p *TextBlock) GetText() (v string) {
	return p.Text
}

func (p *TextBlock) GetConfidence() (v float64) {
	return p.Confidence
}

var TextBlock_BoundingBox_DEFAULT *Box

func (p *TextBlock) GetBoundingBox() (v *Box) {
	if !p.IsSetBoundingBox() {
		return TextBlock_BoundingBox_DEFAULT
	}
	return p.BoundingBox
}
func (p *TextBlock) SetText(val string) {
	p.Text = val
}
func (p *TextBlock) SetConfidence(val float64) {
	p.Confidence = val
}
func (p *TextBlock) SetBoundingBox(val *Box) {
	p.BoundingBox = val
}

func (p *TextBlock) IsSetBoundingBox() bool {
	return p.BoundingBox != nil
}

func (p *TextBlock) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TextBlock(%+v)", *p)
}

var fieldIDToName_TextBlock = map[int16]string{
	1: "text",
	2: "confidence",
	3: "bounding_box",
}

type RuleEngineService interface {
	Scan(ctx context.Context, req *ScanRequest) (r *ScanResponse, err error)
}

type RuleEngineServiceScanArgs struct {
	Req *ScanRequest `thrift:"req,1" frugal:"1,default,ScanRequest" json:"req"`
}

func NewRuleEngineServiceScanArgs() *RuleEngineServiceScanArgs {
	return &RuleEngineServiceScanArgs{}
}

func (p *RuleEngineServiceScanArgs) InitDefault() {
}

var RuleEngineServiceScanArgs_Req_DEFAULT *ScanRequest

func (p *RuleEngineServiceScanArgs) GetReq() (v *ScanRequest) {
	if !p.IsSetReq() {
		return RuleEngineServiceScanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RuleEngineServiceScanArgs) SetReq(val *ScanRequest) {
	p.Req = val
}

func (p *RuleEngineServiceScanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RuleEngineServiceScanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuleEngineServiceScanArgs(%+v)", *p)
}

var fieldIDToName_RuleEngineServiceScanArgs = map[int16]string{
	1: "req",
}

type RuleEngineServiceScanResult struct {
	Success *ScanResponse `thrift:"success,0,optional" frugal:"0,optional,ScanResponse" json:"success,omitempty"`
}

func NewRuleEngineServiceScanResult() *RuleEngineServiceScanResult {
	return &RuleEngineServiceScanResult{}
}

func (p *RuleEngineServiceScanResult) InitDefault() {
}

var RuleEngineServiceScanResult_Success_DEFAULT *ScanResponse

func (p *RuleEngineServiceScanResult) GetSuccess() (v *ScanResponse) {
	if !p.IsSetSuccess() {
		return RuleEngineServiceScanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RuleEngineServiceScanResult) SetSuccess(x interface{}) {
	p.Success = x.(*ScanResponse)
}

func (p *RuleEngineServiceScanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RuleEngineServiceScanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuleEngineServiceScanResult(%+v)", *p)
}

var fieldIDToName_RuleEngineServiceScanResult = map[int16]string{
	0: "success",
}

type LLMAgentService interface {
	Scan(ctx context.Context, req *ScanRequest) (r *ScanResponse, err error)
}

type LLMAgentServiceScanArgs struct {
	Req *ScanRequest `thrift:"req,1" frugal:"1,default,ScanRequest" json:"req"`
}

func NewLLMAgentServiceScanArgs() *LLMAgentServiceScanArgs {
	return &LLMAgentServiceScanArgs{}
}

func (p *LLMAgentServiceScanArgs) InitDefault() {
}

var LLMAgentServiceScanArgs_Req_DEFAULT *ScanRequest

func (p *LLMAgentServiceScanArgs) GetReq() (v *ScanRequest) {
	if !p.IsSetReq() {
		return LLMAgentServiceScanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LLMAgentServiceScanArgs) SetReq(val *ScanRequest) {
	p.Req = val
}

func (p *LLMAgentServiceScanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LLMAgentServiceScanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LLMAgentServiceScanArgs(%+v)", *p)
}

var fieldIDToName_LLMAgentServiceScanArgs = map[int16]string{
	1: "req",
}

type LLMAgentServiceScanResult struct {
	Success *ScanResponse `thrift:"success,0,optional" frugal:"0,optional,ScanResponse" json:"success,omitempty"`
}

func NewLLMAgentServiceScanResult() *LLMAgentServiceScanResult {
	return &LLMAgentServiceScanResult{}
}

func (p *LLMAgentServiceScanResult) InitDefault() {
}

var LLMAgentServiceScanResult_Success_DEFAULT *ScanResponse

func (p *LLMAgentServiceScanResult) GetSuccess() (v *ScanResponse) {
	if !p.IsSetSuccess() {
		return LLMAgentServiceScanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LLMAgentServiceScanResult) SetSuccess(x interface{}) {
	p.Success = x.(*ScanResponse)
}

func (p *LLMAgentServiceScanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LLMAgentServiceScanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LLMAgentServiceScanResult(%+v)", *p)
}

var fieldIDToName_LLMAgentServiceScanResult = map[int16]string{
	0: "success",
}

type ImageModerationService interface {
	Moderate(ctx context.Context, req *ImageModerationRequest) (r *ImageModerationResponse, err error)
}

type ImageModerationServiceModerateArgs struct {
	Req *ImageModerationRequest `thrift:"req,1" frugal:"1,default,ImageModerationRequest" json:"req"`
}

func NewImageModerationServiceModerateArgs() *ImageModerationServiceModerateArgs {
	return &ImageModerationServiceModerateArgs{}
}

func (p *ImageModerationServiceModerateArgs) InitDefault() {
}

var ImageModerationServiceModerateArgs_Req_DEFAULT *ImageModerationRequest

func (p *ImageModerationServiceModerateArgs) GetReq() (v *ImageModerationRequest) {
	if !p.IsSetReq() {
		return ImageModerationServiceModerateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ImageModerationServiceModerateArgs) SetReq(val *ImageModerationRequest) {
	p.Req = val
}

func (p *ImageModerationServiceModerateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ImageModerationServiceModerateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageModerationServiceModerateArgs(%+v)", *p)
}

var fieldIDToName_ImageModerationServiceModerateArgs = map[int16]string{
	1: "req",
}

type ImageModerationServiceModerateResult struct {
	Success *ImageModerationResponse `thrift:"success,0,optional" frugal:"0,optional,ImageModerationResponse" json:"success,omitempty"`
}

func NewImageModerationServiceModerateResult() *ImageModerationServiceModerateResult {
	return &ImageModerationServiceModerateResult{}
}

func (p *ImageModerationServiceModerateResult) InitDefault() {
}

var ImageModerationServiceModerateResult_Success_DEFAULT *ImageModerationResponse

func (p *ImageModerationServiceModerateResult) GetSuccess() (v *ImageModerationResponse) {
	if !p.IsSetSuccess() {
		return ImageModerationServiceModerateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ImageModerationServiceModerateResult) SetSuccess(x interface{}) {
	p.Success = x.(*ImageModerationResponse)
}

func (p *ImageModerationServiceModerateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ImageModerationServiceModerateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageModerationServiceModerateResult(%+v)", *p)
}

var fieldIDToName_ImageModerationServiceModerateResult = map[int16]string{
	0: "success",
}
