// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package safeflow

import (
	"context"
	"fmt"
)

type ScanRequest struct {
	RequestId string `thrift:"request_id,1" frugal:"1,default,string" json:"request_id"`
	UserId    string `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	Content   string `thrift:"content,3" frugal:"3,default,string" json:"content"`
}

func NewScanRequest() *ScanRequest {
	return &ScanRequest{}
}

func (p *ScanRequest) InitDefault() {
}

func (p *ScanRequest) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ScanRequest) GetUserId() (v string) {
	return p.UserId
}

func (p *ScanRequest) GetContent() (v string) {
	return p.Content
}
func (p *ScanRequest) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ScanRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *ScanRequest) SetContent(val string) {
	p.Content = val
}

func (p *ScanRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScanRequest(%+v)", *p)
}

var fieldIDToName_ScanRequest = map[int16]string{
	1: "request_id",
	2: "user_id",
	3: "content",
}

type ScanResponse struct {
	RequestId string `thrift:"request_id,1" frugal:"1,default,string" json:"request_id"`
	Action    string `thrift:"action,2" frugal:"2,default,string" json:"action"`
	Reason    string `thrift:"reason,3" frugal:"3,default,string" json:"reason"`
	Source    string `thrift:"source,4" frugal:"4,default,string" json:"source"`
}

func NewScanResponse() *ScanResponse {
	return &ScanResponse{}
}

func (p *ScanResponse) InitDefault() {
}

func (p *ScanResponse) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ScanResponse) GetAction() (v string) {
	return p.Action
}

func (p *ScanResponse) GetReason() (v string) {
	return p.Reason
}

func (p *ScanResponse) GetSource() (v string) {
	return p.Source
}
func (p *ScanResponse) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ScanResponse) SetAction(val string) {
	p.Action = val
}
func (p *ScanResponse) SetReason(val string) {
	p.Reason = val
}
func (p *ScanResponse) SetSource(val string) {
	p.Source = val
}

func (p *ScanResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScanResponse(%+v)", *p)
}

var fieldIDToName_ScanResponse = map[int16]string{
	1: "request_id",
	2: "action",
	3: "reason",
	4: "source",
}

type RuleEngineService interface {
	Scan(ctx context.Context, req *ScanRequest) (r *ScanResponse, err error)
}

type RuleEngineServiceScanArgs struct {
	Req *ScanRequest `thrift:"req,1" frugal:"1,default,ScanRequest" json:"req"`
}

func NewRuleEngineServiceScanArgs() *RuleEngineServiceScanArgs {
	return &RuleEngineServiceScanArgs{}
}

func (p *RuleEngineServiceScanArgs) InitDefault() {
}

var RuleEngineServiceScanArgs_Req_DEFAULT *ScanRequest

func (p *RuleEngineServiceScanArgs) GetReq() (v *ScanRequest) {
	if !p.IsSetReq() {
		return RuleEngineServiceScanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RuleEngineServiceScanArgs) SetReq(val *ScanRequest) {
	p.Req = val
}

func (p *RuleEngineServiceScanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RuleEngineServiceScanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuleEngineServiceScanArgs(%+v)", *p)
}

var fieldIDToName_RuleEngineServiceScanArgs = map[int16]string{
	1: "req",
}

type RuleEngineServiceScanResult struct {
	Success *ScanResponse `thrift:"success,0,optional" frugal:"0,optional,ScanResponse" json:"success,omitempty"`
}

func NewRuleEngineServiceScanResult() *RuleEngineServiceScanResult {
	return &RuleEngineServiceScanResult{}
}

func (p *RuleEngineServiceScanResult) InitDefault() {
}

var RuleEngineServiceScanResult_Success_DEFAULT *ScanResponse

func (p *RuleEngineServiceScanResult) GetSuccess() (v *ScanResponse) {
	if !p.IsSetSuccess() {
		return RuleEngineServiceScanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RuleEngineServiceScanResult) SetSuccess(x interface{}) {
	p.Success = x.(*ScanResponse)
}

func (p *RuleEngineServiceScanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RuleEngineServiceScanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuleEngineServiceScanResult(%+v)", *p)
}

var fieldIDToName_RuleEngineServiceScanResult = map[int16]string{
	0: "success",
}

type LLMAgentService interface {
	Scan(ctx context.Context, req *ScanRequest) (r *ScanResponse, err error)
}

type LLMAgentServiceScanArgs struct {
	Req *ScanRequest `thrift:"req,1" frugal:"1,default,ScanRequest" json:"req"`
}

func NewLLMAgentServiceScanArgs() *LLMAgentServiceScanArgs {
	return &LLMAgentServiceScanArgs{}
}

func (p *LLMAgentServiceScanArgs) InitDefault() {
}

var LLMAgentServiceScanArgs_Req_DEFAULT *ScanRequest

func (p *LLMAgentServiceScanArgs) GetReq() (v *ScanRequest) {
	if !p.IsSetReq() {
		return LLMAgentServiceScanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LLMAgentServiceScanArgs) SetReq(val *ScanRequest) {
	p.Req = val
}

func (p *LLMAgentServiceScanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LLMAgentServiceScanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LLMAgentServiceScanArgs(%+v)", *p)
}

var fieldIDToName_LLMAgentServiceScanArgs = map[int16]string{
	1: "req",
}

type LLMAgentServiceScanResult struct {
	Success *ScanResponse `thrift:"success,0,optional" frugal:"0,optional,ScanResponse" json:"success,omitempty"`
}

func NewLLMAgentServiceScanResult() *LLMAgentServiceScanResult {
	return &LLMAgentServiceScanResult{}
}

func (p *LLMAgentServiceScanResult) InitDefault() {
}

var LLMAgentServiceScanResult_Success_DEFAULT *ScanResponse

func (p *LLMAgentServiceScanResult) GetSuccess() (v *ScanResponse) {
	if !p.IsSetSuccess() {
		return LLMAgentServiceScanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LLMAgentServiceScanResult) SetSuccess(x interface{}) {
	p.Success = x.(*ScanResponse)
}

func (p *LLMAgentServiceScanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LLMAgentServiceScanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LLMAgentServiceScanResult(%+v)", *p)
}

var fieldIDToName_LLMAgentServiceScanResult = map[int16]string{
	0: "success",
}
